/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.waluciarz;

import java.io.File;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author adrianziebowski
 */
public class Waluciarz extends javax.swing.JFrame {

    /**
     * Creates new form Waluciarz
     */
    public Waluciarz() {
        initComponents();
        jL_error.setText("");
        
        GetData getData = new GetData();
        waluty = getData.get();
        
        ArrayList<String> codeList = new ArrayList<>();
        for (Waluta waluta : waluty) {
            codeList.add(waluta.getCurrency());
        }
        jComboBox_wybierzWaluty.setModel(new DefaultComboBoxModel(codeList.toArray()));
        updateView();
        initLists();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox_wybierzWaluty = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jComboBox_wybierzDzialanie = new javax.swing.JComboBox<>();
        jLabel_ilosc = new javax.swing.JLabel();
        jLabel_przeliczonaKwota = new javax.swing.JLabel();
        jTextField_kwota = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jL_error = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_kurs = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButton_loadData = new javax.swing.JButton();
        jComboBox_loadType = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_data = new javax.swing.JTextArea();
        jComboBox_chooseSorting = new javax.swing.JComboBox<>();
        jComboBox_chooseAscending = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));

        jTabbedPane1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Kantor Walut");

        jLabel2.setText("Wybierz walute:");

        jComboBox_wybierzWaluty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Waluty" }));
        jComboBox_wybierzWaluty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_wybierzWalutyActionPerformed(evt);
            }
        });

        jLabel3.setText("Kupno/Sprzedaż:");

        jComboBox_wybierzDzialanie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kupno", "Sprzedaz" }));
        jComboBox_wybierzDzialanie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_wybierzDzialanieActionPerformed(evt);
            }
        });

        jLabel_ilosc.setText("Kwota [XXX]: ");

        jLabel_przeliczonaKwota.setText("Przeliczona kwota [XXX]:");

        jButton1.setText("Przelicz");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jL_error.setText("err");

        jLabel4.setText("Kurs: ");

        jTextField_kurs.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jL_error, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_ilosc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_przeliczonaKwota, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBox_wybierzDzialanie, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField_kwota)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_kurs))
                            .addComponent(jComboBox_wybierzWaluty, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox_wybierzWaluty)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField_kurs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jComboBox_wybierzDzialanie)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_ilosc, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_kwota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_przeliczonaKwota, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jL_error, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Kantor", jPanel1);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jButton_loadData.setText("Wczytaj");
        jButton_loadData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_loadDataActionPerformed(evt);
            }
        });

        jComboBox_loadType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kupno", "Sprzedaż" }));
        jComboBox_loadType.setEnabled(false);
        jComboBox_loadType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_loadTypeActionPerformed(evt);
            }
        });

        jTextArea_data.setColumns(20);
        jTextArea_data.setRows(5);
        jScrollPane1.setViewportView(jTextArea_data);

        jComboBox_chooseSorting.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Przelicznik", "Kwota przeliczona", "Początkowa kwota" }));
        jComboBox_chooseSorting.setEnabled(false);
        jComboBox_chooseSorting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_chooseSortingActionPerformed(evt);
            }
        });

        jComboBox_chooseAscending.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Malejąco", "Rosnąco" }));
        jComboBox_chooseAscending.setEnabled(false);
        jComboBox_chooseAscending.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_chooseAscendingActionPerformed(evt);
            }
        });

        jLabel5.setText("Sortuj według:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton_loadData)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox_loadType, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox_chooseSorting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox_chooseAscending, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_loadData)
                    .addComponent(jComboBox_loadType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox_chooseSorting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_chooseAscending, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Odczyt", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox_wybierzWalutyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_wybierzWalutyActionPerformed
        currentWalutaId = jComboBox_wybierzWaluty.getSelectedIndex();
        updateView();
    }//GEN-LAST:event_jComboBox_wybierzWalutyActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String kwotaText = jTextField_kwota.getText();
        
        String err = "";
        if(kwotaText.equals("")) {
            jL_error.setText("Prosze podac kwote");
        }
        else try {
            double kwota = Double.parseDouble(kwotaText);
            Waluta waluta = waluty.get(currentWalutaId);
            ZapisDoPliku zapisDoPliku = new ZapisDoPliku(f);
            
            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");  
            LocalDateTime now = LocalDateTime.now();  
            String date = dtf.format(now);
            String textDoZapisu = date+";"+waluta.getCode()+";";
//          code;actType;wal;pln;kurs;
//          code;actType;pln;wal;kurs;
            double przeliczonaWaluta;
            if(currentActionId == 1) {
                //sprzedaz
                waluta.calcBidPrize(kwota);
                przeliczonaWaluta = waluta.getBidPrize();
                textDoZapisu += "s;"+kwota+";"+przeliczonaWaluta+";"+waluta.getBid();
            } else {
                //kupno
                waluta.calcAskPrize(kwota);
                przeliczonaWaluta = waluta.getAskPrize();
                textDoZapisu += "k;"+kwota+";"+przeliczonaWaluta+";"+waluta.getAsk();
            }
            
            zapisDoPliku.zapisz(textDoZapisu);
            jTextField2.setText(przeliczonaWaluta+"");
            jL_error.setText("");
        } catch(Exception ex) {
            jL_error.setText("To nie jest liczba");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox_wybierzDzialanieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_wybierzDzialanieActionPerformed
        currentActionId = jComboBox_wybierzDzialanie.getSelectedIndex();
        updateView();
    }//GEN-LAST:event_jComboBox_wybierzDzialanieActionPerformed

    private void jButton_loadDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_loadDataActionPerformed
        enableElems();
        initLists();
        sort();
        updateViewOfData();
    }//GEN-LAST:event_jButton_loadDataActionPerformed

    private void jComboBox_chooseSortingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_chooseSortingActionPerformed
        sort();
        updateViewOfData();
    }//GEN-LAST:event_jComboBox_chooseSortingActionPerformed

    private void jComboBox_loadTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_loadTypeActionPerformed
        updateViewOfData();
    }//GEN-LAST:event_jComboBox_loadTypeActionPerformed

    private void jComboBox_chooseAscendingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_chooseAscendingActionPerformed
        sort();
        updateViewOfData();
    }//GEN-LAST:event_jComboBox_chooseAscendingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Waluciarz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Waluciarz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Waluciarz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Waluciarz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Waluciarz().setVisible(true);
            }
        });
    }
    
    /**
     * nazwa funkcji: updateView
     * argumenty: brak
     * typ  zwracany: brak
     * informacje: odswieza wyglad w przypadku zmiany kupna/sprzedazy
     * autor: Szymon Rychter
     */
    private void updateView() {
        final String code = waluty.get(currentWalutaId).getCode();
        if(currentActionId == 1) {
            //sprzedaz
            jLabel_ilosc.setText("Kwota w "+code+": ");
            jLabel_przeliczonaKwota.setText("Przeliczona kwota [PLN]: ");
        } else {
            //kupno
            jLabel_ilosc.setText("Kwota w PLN: ");
            jLabel_przeliczonaKwota.setText("Przeliczona kwota ["+code+"]: ");
        }
        updateKurs();
    }
    
    /**
     * nazwa funkcji: updateKurs
     * argumenty: brak
     * typ  zwracany: brak
     * informacje: uaktualnia kurs w wygladzie
     * autor: Szymon Rychter
     */
    private void updateKurs() {
        double kurs = waluty.get(currentWalutaId).getAsk();
        if(currentActionId == 1) {
            kurs = waluty.get(currentWalutaId).getBid();
        }
        jTextField_kurs.setText(kurs+"");
    }
    
    /**
     * nazwa funkcji: initLists
     * argumenty: brak
     * typ  zwracany: brak
     * informacje: odczytuje dane z pliku i zapisuje do list
     * autor: Szymon Rychter
     */
    private void initLists() {
        ZapisDoPliku zapisDoPliku = new ZapisDoPliku(f);
        Map<String, ArrayList<FileData>> map = zapisDoPliku.odczyt();
        listaSprzedazy = map.get("listaSprzedazy");
        listaKupna = map.get("listaKupna");
    }
    
    /**
     * nazwa funkcji: sort
     * argumenty: brak
     * typ  zwracany: brak
     * informacje: sortuje listy
     * autor: Szymon Rychter
     */
    private void sort() {
        int index = jComboBox_chooseSorting.getSelectedIndex();

        Comparator comp = null;
        switch (index) {
            case 0 -> comp = Comparator.comparing(FileData::getMultiplayer);
            case 1 -> comp = Comparator.comparing(FileData::getFinalPrize);
            case 2 -> comp = Comparator.comparing(FileData::getPrize);
            default -> {
            }
        }

        if(jComboBox_chooseAscending.getSelectedIndex() == 0) {
            comp = comp.reversed();
        } 
        listaKupna.sort(comp);
        listaSprzedazy.sort(comp);
        updateViewOfData();
        
    }
    
    /**
     * nazwa funkcji: enableElems
     * argumenty: brak
     * typ  zwracany: brak
     * informacje: umozliwia klikniecie przyciskow
     * autor: Szymon Rychter
     */
    private void enableElems() {
        jComboBox_loadType.setEnabled(true);
        jComboBox_chooseSorting.setEnabled(true);
        jComboBox_chooseAscending.setEnabled(true);
    }
    
    /**
     * nazwa funkcji: updateViewOfData
     * argumenty: brak
     * typ  zwracany: brak
     * informacje: wypisuje listy do jTextArea_data
     * autor: Szymon Rychter
     */
    private void updateViewOfData() {
        int index = jComboBox_loadType.getSelectedIndex();

        if(index == 0) {
            //kupno
            String text = "";
            for (FileData fileData : listaKupna) {
                text += fileData.toString();
            }
            
            jTextArea_data.setText(text);
        } else {
            String text = "";
            for (FileData fileData : listaSprzedazy) {
                text += fileData.toString();
            }
            
            jTextArea_data.setText(text);
        }
    }
    
    private ArrayList<FileData> listaSprzedazy;
    private ArrayList<FileData> listaKupna;
    private int currentWalutaId = 0;
    private int currentActionId = 0;
    ArrayList<Waluta> waluty = new ArrayList<>();
    File f = new File("data.txt");

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_loadData;
    private javax.swing.JComboBox<String> jComboBox_chooseAscending;
    private javax.swing.JComboBox<String> jComboBox_chooseSorting;
    private javax.swing.JComboBox<String> jComboBox_loadType;
    private javax.swing.JComboBox<String> jComboBox_wybierzDzialanie;
    private javax.swing.JComboBox<String> jComboBox_wybierzWaluty;
    private javax.swing.JLabel jL_error;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_ilosc;
    private javax.swing.JLabel jLabel_przeliczonaKwota;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea_data;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField_kurs;
    private javax.swing.JTextField jTextField_kwota;
    // End of variables declaration//GEN-END:variables
}
