/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.chodzacz;

import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 * App that shows routes
 * @author Szymon
 */
public class Chodzacz extends javax.swing.JFrame {

    /**
     * Creates new form Chodzacz
     */
    public Chodzacz() {
        initComponents();
        setLocationRelativeTo(null);
        setComboBoxValues(); // set default comboBox values (being webscraped from database)
        setVisibilityOfComponents(false); // hide components that show route information (since they are empty)
        jL_img.setText(""); // set text to jLabel that will be image of route
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jCB_chooseRoute = new javax.swing.JComboBox<>();
        jL_name = new javax.swing.JLabel();
        jTF_name = new javax.swing.JTextField();
        jL_type = new javax.swing.JLabel();
        jTF_type = new javax.swing.JTextField();
        jL_length = new javax.swing.JLabel();
        jTF_length = new javax.swing.JTextField();
        jL_bestTime = new javax.swing.JLabel();
        jTF_bestTime = new javax.swing.JTextField();
        jL_img = new javax.swing.JLabel();
        jCB_sort = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMI_saveRouteToFile = new javax.swing.JMenuItem();
        jMI_closeApp = new javax.swing.JMenuItem();
        jMI_aboutApp = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chodzacz");

        jCB_chooseRoute.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Wybierz trasę" }));
        jCB_chooseRoute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCB_chooseRouteActionPerformed(evt);
            }
        });

        jL_name.setText("Nazwa: ");

        jTF_name.setEditable(false);

        jL_type.setText("Typ:");

        jTF_type.setEditable(false);

        jL_length.setText("Długość [m]:");

        jTF_length.setEditable(false);

        jL_bestTime.setText("Najlepszy czas [s]:");

        jTF_bestTime.setEditable(false);

        jL_img.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_img.setText("img");

        jCB_sort.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sortuj trasy według", "Nazwy", "Długości", "Typu" }));
        jCB_sort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCB_sortActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jCB_chooseRoute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCB_sort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jL_bestTime, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jL_length, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jL_type, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jL_name, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTF_name, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(jTF_type)
                            .addComponent(jTF_length)
                            .addComponent(jTF_bestTime)))
                    .addComponent(jL_img, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCB_chooseRoute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCB_sort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_name, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTF_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_type, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTF_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_length, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTF_length, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_bestTime, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTF_bestTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jL_img, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("Opcje");

        jMI_saveRouteToFile.setText("Zapisz trasę do pliku");
        jMI_saveRouteToFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_saveRouteToFileActionPerformed(evt);
            }
        });
        jMenu1.add(jMI_saveRouteToFile);

        jMI_closeApp.setText("Zamknij aplikacje");
        jMI_closeApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_closeAppActionPerformed(evt);
            }
        });
        jMenu1.add(jMI_closeApp);

        jMI_aboutApp.setText("O programie");
        jMI_aboutApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_aboutAppActionPerformed(evt);
            }
        });
        jMenu1.add(jMI_aboutApp);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCB_chooseRouteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCB_chooseRouteActionPerformed
        selectRoute();
    }//GEN-LAST:event_jCB_chooseRouteActionPerformed

    private void jCB_sortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCB_sortActionPerformed
        sortComboBox(jCB_sort.getSelectedIndex());
    }//GEN-LAST:event_jCB_sortActionPerformed

    private void jMI_closeAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_closeAppActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMI_closeAppActionPerformed

    private void jMI_aboutAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_aboutAppActionPerformed
        JOptionPane.showMessageDialog(null, "To jest aplikacja, która wyświetla dane o trasach.\nWykonana przez Szymona Rychtera i Mateusza Suchockiego", "O programie", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMI_aboutAppActionPerformed

    private void jMI_saveRouteToFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_saveRouteToFileActionPerformed
        boolean save = saveRouteToFile();
        if(!save) {
            JOptionPane.showMessageDialog(null, "Nie ma wybranej trasy lub nie wprowadzono nazwy pliku", "Błąd", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jMI_saveRouteToFileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Chodzacz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Chodzacz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Chodzacz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Chodzacz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Chodzacz().setVisible(true);
            }
        });
    }

    /**
     * Sets the default comboBox values from list 'routes'
     */
    private void setComboBoxValues() {
        List<String> names = new ArrayList<>();
        names.add("Wybierz trasę");
        for(Route r : routes) {
            names.add(r.getName());
        }
        
        jCB_chooseRoute.setModel(new DefaultComboBoxModel(names.toArray()));
    }
    
    /**
     * Sets visiblity of components that show information about selected route
     * @param visible true - shows elements | false - hides elements
     */
    private void setVisibilityOfComponents(boolean visible) {
        jTF_name.setVisible(visible);
        jTF_type.setVisible(visible);
        jTF_length.setVisible(visible);
        jTF_bestTime.setVisible(visible);
        jL_name.setVisible(visible);
        jL_type.setVisible(visible);
        jL_length.setVisible(visible);
        jL_bestTime.setVisible(visible);
        jL_img.setVisible(visible);
    }
    
    /**
     * Shows informations about selected route
     */
    private void changeView() {
        jTF_name.setText(route.getName());
        jTF_type.setText(route.getType());
        jTF_length.setText(""+route.getLength());
        jTF_bestTime.setText(""+route.getBestLapTime());
        
        URL url;
        try {
            url = new URL(route.getImgageUrl());
            Image image = ImageIO.read(url);
            
            // scale image (average ratio = 1.5 [width/height])
            image = image.getScaledInstance(495, 330,  java.awt.Image.SCALE_SMOOTH);

            jL_img.setIcon(new ImageIcon(image));
        } catch (MalformedURLException ex) {
            Logger.getLogger(Chodzacz.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Chodzacz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * Sets the selected route to variable 'route'
     */
    private void selectRoute() {
        String comboBoxValue = jCB_chooseRoute.getSelectedItem().toString();
        
        for(int i = 0; i < routes.size(); i++) {
           if(routes.get(i).getName().equals(comboBoxValue)) route = routes.get(i);
        }
        
        if(route != null) {
            setVisibilityOfComponents(true);
            changeView();
        } else setVisibilityOfComponents(false);
    }
    
    /**
     * Sorts routeList by index
     * @param index  
     * 1: name
     * 2: length
     * 3: type
     */
    private void sortComboBox(int index) {
        switch (index) {
            case 1 -> {
                //sortowanie wedlug nazwy
                routes.sort(Comparator.comparing(Route::getName));
                setComboBoxValues();
            }
            case 2 -> {
                //sortowanie według długości
                routes.sort(Comparator.comparing(Route::getLength));
                setComboBoxValues();
            }
            case 3 -> {
                //sortowanie według typu
                routes.sort(Comparator.comparing(Route::getType));
                setComboBoxValues();
            }
            default -> {
            }
        }
    }
    
    /**
     * Saves route to selected directory and file name
     * @return returns false if route is null. Else return true
     */
    private boolean saveRouteToFile() {
        if(route == null) return false;
        
        JFileChooser chooser = new JFileChooser(); 
        chooser.setCurrentDirectory(new java.io.File("."));
        chooser.setDialogTitle("Wybierz folder w którym mają zostać zapisane dane");
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        
        chooser.setAcceptAllFileFilterUsed(false);
        
        String dir = null;
        if(chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) { 
            dir = chooser.getSelectedFile().toString();
        } else System.out.println("Nie wybrano folderu");
        
        if(dir != null) {
            String separator = System.getProperty("file.separator");
            
            String fileName = JOptionPane.showInputDialog("Podaj nazwe pliku");
            if(fileName.equals("")) return false;
            File f = new File(dir+separator+fileName+".txt");
            System.out.println(f.toString());        
            
            if(!fileName.equals("")) {
                SaveToFile stf = new SaveToFile();
                stf.save(f, route.toString());
            }
        } 
        
        return true;
    }
    
    RouteImp route = null; //selected route
    ArrayList<Route> routes = new Routes().getRouteList();
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jCB_chooseRoute;
    private javax.swing.JComboBox<String> jCB_sort;
    private javax.swing.JLabel jL_bestTime;
    private javax.swing.JLabel jL_img;
    private javax.swing.JLabel jL_length;
    private javax.swing.JLabel jL_name;
    private javax.swing.JLabel jL_type;
    private javax.swing.JMenuItem jMI_aboutApp;
    private javax.swing.JMenuItem jMI_closeApp;
    private javax.swing.JMenuItem jMI_saveRouteToFile;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTF_bestTime;
    private javax.swing.JTextField jTF_length;
    private javax.swing.JTextField jTF_name;
    private javax.swing.JTextField jTF_type;
    // End of variables declaration//GEN-END:variables
}