/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.com.szymon.rychter.listazakupw;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.io.FileWriter;
import java.io.IOException;

/**
 *
 * @author Szymon
 */
public class ListaZakupow extends javax.swing.JFrame {

    /**
     * Creates new form ListaZakupow
     */
    public ListaZakupow() {
        initComponents();
        addKeyListenerTosr_jTextField_insertName();
        addKeyListenerTosr_jTextField_insertValue();
        addKeyListenerTosr_jTextField_date();
        addTooltipToElements();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sr_jTabbedPane = new javax.swing.JTabbedPane();
        sr_jPanel_insertData = new javax.swing.JPanel();
        sr_jLabel_insertName = new javax.swing.JLabel();
        sr_jTextField_insertName = new javax.swing.JTextField();
        sr_jLabel_insertValue = new javax.swing.JLabel();
        sr_jTextField_insertValue = new javax.swing.JTextField();
        sr_jLabel_today = new javax.swing.JLabel();
        sr_jLabel_typeOfProduct = new javax.swing.JLabel();
        sr_jComboBox_typeOfProduct = new javax.swing.JComboBox<>();
        sr_jLabel_date = new javax.swing.JLabel();
        sr_jTextField_date = new javax.swing.JTextField();
        sr_jButton_save = new javax.swing.JButton();
        sr_jLabel_todayCost = new javax.swing.JLabel();
        sr_jLabel_weeklyCost = new javax.swing.JLabel();
        sr_jTextField_weeklyCost = new javax.swing.JTextField();
        sr_jTextField_todayCost = new javax.swing.JTextField();
        sr_jScrollPane = new javax.swing.JScrollPane();
        sr_jTextArea_today = new javax.swing.JTextArea();
        sr_jPanel_insert = new javax.swing.JPanel();
        sr_jMenuBar = new javax.swing.JMenuBar();
        sr_jMenu_file = new javax.swing.JMenu();
        sr_jMenu_edit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sr_jLabel_insertName.setText("Wpisz co kupiłeś");

        sr_jTextField_insertName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sr_jTextField_insertNameActionPerformed(evt);
            }
        });

        sr_jLabel_insertValue.setText("Podaj wartość");

        sr_jLabel_today.setText("Dzisiejsze zakupy");

        sr_jLabel_typeOfProduct.setText("Typ zakupionego towaru");

        sr_jComboBox_typeOfProduct.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        sr_jLabel_date.setText("Data zakupu");

        sr_jTextField_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sr_jTextField_dateActionPerformed(evt);
            }
        });

        sr_jButton_save.setText("ZAPISZ");
        sr_jButton_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sr_jButton_saveActionPerformed(evt);
            }
        });

        sr_jLabel_todayCost.setText("Wydatki z dzisiaj:");

        sr_jLabel_weeklyCost.setText("Wydatki z tygodnia:");

        sr_jTextField_todayCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sr_jTextField_todayCostActionPerformed(evt);
            }
        });

        sr_jTextArea_today.setColumns(20);
        sr_jTextArea_today.setRows(5);
        sr_jScrollPane.setViewportView(sr_jTextArea_today);

        javax.swing.GroupLayout sr_jPanel_insertDataLayout = new javax.swing.GroupLayout(sr_jPanel_insertData);
        sr_jPanel_insertData.setLayout(sr_jPanel_insertDataLayout);
        sr_jPanel_insertDataLayout.setHorizontalGroup(
            sr_jPanel_insertDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sr_jPanel_insertDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sr_jPanel_insertDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sr_jPanel_insertDataLayout.createSequentialGroup()
                        .addComponent(sr_jLabel_today)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(sr_jPanel_insertDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(sr_jPanel_insertDataLayout.createSequentialGroup()
                                .addGroup(sr_jPanel_insertDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(sr_jLabel_typeOfProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(sr_jComboBox_typeOfProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(sr_jPanel_insertDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(sr_jLabel_date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(sr_jTextField_date)))
                            .addComponent(sr_jButton_save, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(sr_jPanel_insertDataLayout.createSequentialGroup()
                        .addGroup(sr_jPanel_insertDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(sr_jPanel_insertDataLayout.createSequentialGroup()
                                .addGroup(sr_jPanel_insertDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(sr_jPanel_insertDataLayout.createSequentialGroup()
                                        .addComponent(sr_jLabel_insertName)
                                        .addGap(0, 176, Short.MAX_VALUE))
                                    .addComponent(sr_jTextField_insertName))
                                .addGap(18, 18, 18)
                                .addGroup(sr_jPanel_insertDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sr_jLabel_insertValue)
                                    .addComponent(sr_jTextField_insertValue, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(sr_jScrollPane))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(sr_jPanel_insertDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(sr_jPanel_insertDataLayout.createSequentialGroup()
                                .addComponent(sr_jLabel_todayCost)
                                .addGap(30, 30, 30)
                                .addComponent(sr_jTextField_todayCost))
                            .addGroup(sr_jPanel_insertDataLayout.createSequentialGroup()
                                .addComponent(sr_jLabel_weeklyCost, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sr_jTextField_weeklyCost, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        sr_jPanel_insertDataLayout.setVerticalGroup(
            sr_jPanel_insertDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sr_jPanel_insertDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sr_jPanel_insertDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(sr_jPanel_insertDataLayout.createSequentialGroup()
                        .addGroup(sr_jPanel_insertDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sr_jLabel_insertName)
                            .addComponent(sr_jLabel_insertValue)
                            .addComponent(sr_jLabel_typeOfProduct)
                            .addComponent(sr_jLabel_date))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(sr_jPanel_insertDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sr_jTextField_insertName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sr_jTextField_insertValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sr_jComboBox_typeOfProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sr_jTextField_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addComponent(sr_jLabel_today))
                    .addComponent(sr_jButton_save))
                .addGroup(sr_jPanel_insertDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sr_jPanel_insertDataLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(sr_jPanel_insertDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sr_jLabel_todayCost)
                            .addComponent(sr_jTextField_todayCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(sr_jPanel_insertDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sr_jLabel_weeklyCost)
                            .addComponent(sr_jTextField_weeklyCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(sr_jPanel_insertDataLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sr_jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        sr_jTabbedPane.addTab("Wprowadź zakupy", sr_jPanel_insertData);

        javax.swing.GroupLayout sr_jPanel_insertLayout = new javax.swing.GroupLayout(sr_jPanel_insert);
        sr_jPanel_insert.setLayout(sr_jPanel_insertLayout);
        sr_jPanel_insertLayout.setHorizontalGroup(
            sr_jPanel_insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 595, Short.MAX_VALUE)
        );
        sr_jPanel_insertLayout.setVerticalGroup(
            sr_jPanel_insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 551, Short.MAX_VALUE)
        );

        sr_jTabbedPane.addTab("Lista zakupów", sr_jPanel_insert);

        sr_jMenu_file.setText("File");
        sr_jMenuBar.add(sr_jMenu_file);

        sr_jMenu_edit.setText("Edit");
        sr_jMenuBar.add(sr_jMenu_edit);

        setJMenuBar(sr_jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sr_jTabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sr_jTabbedPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sr_jTextField_todayCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sr_jTextField_todayCostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sr_jTextField_todayCostActionPerformed

    private void sr_jTextField_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sr_jTextField_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sr_jTextField_dateActionPerformed

    private void sr_jTextField_insertNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sr_jTextField_insertNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sr_jTextField_insertNameActionPerformed

    private void sr_jButton_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sr_jButton_saveActionPerformed
        String data = sr_jTextArea_today.getText()+sr_jTextField_insertName.getText()+"; "+sr_jTextField_insertValue.getText()+"; "+sr_jComboBox_typeOfProduct.getSelectedItem()+"; "+sr_jTextField_date.getText()+";\n";
        sr_jTextArea_today.setText(data);
        clear();
        try{
            FileWriter fw = new FileWriter(file_name, true);
            fw.write(data.replaceAll("; ", ";"));
            fw.close();
        }catch(IOException ex){
            System.out.println(ex.toString());
        }
    }//GEN-LAST:event_sr_jButton_saveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaZakupow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaZakupow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaZakupow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaZakupow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaZakupow().setVisible(true);
            }
        });
    }

    private void addKeyListenerTosr_jTextField_insertName(){
        sr_jTextField_insertName.addKeyListener(new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {
//                if(e.getKeyChar() == KeyEvent.VK_ENTER){
//                    System.out.println("Wprowadzono dane: ");
//                    sr_jTextField_insertName.setText(sr_jTextField_insertName.getText());
//                }
                char ch = e.getKeyChar();
                if((ch >= 'A' && ch <= 'z') || ch == KeyEvent.VK_BACK_SPACE || ch == KeyEvent.VK_SPACE){
                    sr_jTextField_insertName.setEditable(true);
                    System.out.println("Nacisnieto: "+ch);
                }else sr_jTextField_insertName.setEditable(false);
            }

            @Override
            public void keyPressed(KeyEvent e) {
                
            }

            @Override
            public void keyReleased(KeyEvent e) {
                
            }
        });
    }
    
    int state = 1;
    
    private void addKeyListenerTosr_jTextField_insertValue(){
        sr_jTextField_insertValue.addKeyListener(new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {
                char ch = e.getKeyChar();
                String temp = sr_jTextField_insertValue.getText(); 
                if(temp.contains(".")){
                    if(temp.indexOf(".") == temp.length()+2){
                        
                    }else{
                        System.out.print(temp.indexOf(".")+"  "+temp.length());
                        if((ch >= '0' && ch <= '9') || ch == KeyEvent.VK_BACK_SPACE){
                            sr_jTextField_insertValue.setEditable(true);

                            //System.out.println("Nacisnieto cyfre "+ch);
                        }else sr_jTextField_insertValue.setEditable(false);
                    }
                }else{
                    if((ch >= '0' && ch <= '9') || ch == KeyEvent.VK_BACK_SPACE || ch == KeyEvent.VK_PERIOD){
                        sr_jTextField_insertValue.setEditable(true);

                        //System.out.println("Nacisnieto cyfre "+ch);
                    }else sr_jTextField_insertValue.setEditable(false);
                }
                
            }

            @Override
            public void keyPressed(KeyEvent e) {
                
            }

            @Override
            public void keyReleased(KeyEvent e) {
                
            }
        });
    }
    
    private void addKeyListenerTosr_jTextField_date(){
        sr_jTextField_date.addKeyListener(new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {
                String temp = sr_jTextField_date.getText();
                char ch = e.getKeyChar();
                if((ch >= '0' && ch <= '9' || ch == KeyEvent.VK_BACK_SPACE) && (temp.length()<10 || ch == KeyEvent.VK_BACK_SPACE)){
                    sr_jTextField_date.setEditable(true);
                    if((temp.length() == 4 || temp.length() == 7) && ch != KeyEvent.VK_BACK_SPACE){
                        sr_jTextField_date.setText(temp+"-");
                    }
                    //System.out.println("Nacisnieto cyfre "+ch);
                }else sr_jTextField_date.setEditable(false);
            }

            @Override
            public void keyPressed(KeyEvent e) {
                
            }

            @Override
            public void keyReleased(KeyEvent e) {
                
            }
        });
    }
    
    private void clear(){
        sr_jTextField_insertName.setText("");
        sr_jTextField_insertValue.setText("");
        sr_jTextField_date.setText("");
    }
    
    private void addTooltipToElements(){
        sr_jTextField_insertName.setToolTipText("<html>"
                +"<h3>Wprowadz tekst</h3>"
                +"<p>Nie uzywaj polskich znakow</p>"
                +"</html>");
        sr_jTextField_insertValue.setToolTipText("<html>"
                +"<h3>Wprowadz liczbę</h3>"
                +"<p>Można użyć kropki</p>"
                +"</html>");
        sr_jComboBox_typeOfProduct.setToolTipText("<html>"
                +"<h3>Wprowadz typ zakupionego produktu</h3>"
                +"</html>");
        sr_jTextField_date.setToolTipText("<html>"
                +"<h3>Wprowadz datę</h3>"
                +"<p>Format: rrrr-mm-dd</p>"
                +"</html>");
    }
    
    private String file_name = "lista_zakopow.csv";
    private String product_names = "product_names.csv";
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton sr_jButton_save;
    private javax.swing.JComboBox<String> sr_jComboBox_typeOfProduct;
    private javax.swing.JLabel sr_jLabel_date;
    private javax.swing.JLabel sr_jLabel_insertName;
    private javax.swing.JLabel sr_jLabel_insertValue;
    private javax.swing.JLabel sr_jLabel_today;
    private javax.swing.JLabel sr_jLabel_todayCost;
    private javax.swing.JLabel sr_jLabel_typeOfProduct;
    private javax.swing.JLabel sr_jLabel_weeklyCost;
    private javax.swing.JMenuBar sr_jMenuBar;
    private javax.swing.JMenu sr_jMenu_edit;
    private javax.swing.JMenu sr_jMenu_file;
    private javax.swing.JPanel sr_jPanel_insert;
    private javax.swing.JPanel sr_jPanel_insertData;
    private javax.swing.JScrollPane sr_jScrollPane;
    private javax.swing.JTabbedPane sr_jTabbedPane;
    private javax.swing.JTextArea sr_jTextArea_today;
    private javax.swing.JTextField sr_jTextField_date;
    private javax.swing.JTextField sr_jTextField_insertName;
    private javax.swing.JTextField sr_jTextField_insertValue;
    private javax.swing.JTextField sr_jTextField_todayCost;
    private javax.swing.JTextField sr_jTextField_weeklyCost;
    // End of variables declaration//GEN-END:variables
}
